### ISSUE TITLE
Proje Architecture

### ISSUE THREAD

**Issue by VB10** [mrcasus/flutterv15#1]
Selam arkadaşlar
Biraz inceledim güzel bir gözüküyor elinize sağlık. Lakin sayfalarda karmaşa ortamı gördüm biraz şöyle yapsak nasıl olur?

- Screen ıcındekı sayfalarımız sadece ekran çizsin orada logic olmasın, yani o sayfayı herhangi bir ViewModel tarzı MVVM bakabilirsiniz bu noktada veya MVC tarzı ayrı bir sınıfta yönetsek sayfanın çizimlerini çok iyi olur. Mobx i basitçe entegre edebilirsiniz veya ChangeNotifier den türeyen bir vm classı yaparsanız ui daki değişiklikleri tetikleyebilrsiniz.
- Sayfalarınızı daha atomic parçalayıp kendi yapılarınızı oluşturabilirsiniz
- AppConstant sınıfınız olsun içerideki tüm statik dataları, textleri oradan türetin derim yönetim ve geliştirme açısından
- EasyLocalization ilede sayfanızı dil desteği verin derim.

Elinize sağık tekrardan kolay gelsin 💯

**Comment by furkankurt** [comment]
Selamlar! Proje benim değil sadece yardım etmek için localde değişiklikler yapıp göndermiştim. Osman Bey'in kendi projesi bu. 

Kolay gelsin, teşekkürler..

**Comment by mrcasus** [comment]
selamlar hocamlarım! öncelikle teşekkür ederim.  dilim döndüğü  kadarıyla yapmaya çalıyorum sizinkiler hocam sayesinde.  bu proje de aslı olan sql veritaban  daki girilen verileri excel atıp daha sonra  çıktı almak istedim için sql lite kulladım.   @furkankurt  hocam konuşmuştuk  hive yada firebase yada mobx excel aktarma  yapamadığımız için bu yolu geçtik suanlık bu yetiyor bana  ileri donük olursa verdiğiniz bilgiyi ve tavsiyeleri dikkat edeceğim.
