### ISSUE TITLE
Dropdown Hatasi

### ISSUE THREAD

**Issue by VB10** [mrcasus/flutterv15#2]
Bu hatanın sebebi dropdown listesine bir sınıf atamaya çalışıyorsunuz ama bu atadığınız sınıftaki idler benzer geldiği zaman veya verdiğiniz ile seçilen eleman tutmadığı zaman sorun yaratıyor
`class DropdownItem {
  String value;
  String title;
  DropdownItem({
    @required this.value,
    @required this.title,
  });

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DropdownItem &&
          runtimeType == other.runtimeType &&
          value == other.value;

  @override
  int get hashCode => value.hashCode;
}` 

Dropdown sınfınızı şu şekilde == opertörün ovveride edicek şekilde yaparsanız sorun çözüleecektir. Kolay gelsin

**Comment by mrcasus** [comment]
geri dönüşünüz için teşekkürler kendimi geliştirmek için bişeyler yapıyorum. (kısaca yeniyim) . bahsettinizden bişey anlamadım. kusara bakmayın. @furkankurt suratında :D tebessüm ederdi.hocam daha açıklayıcı yada kod üstünden bahsedebilir misiniz?
